on:
  push:
    branches:
      - 'main'
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: Building image
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up for build
        id: build_setup
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push to hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ORGANIZATION }}/direwolf:latest
        
