on:
  push:
    branches:
      - 'main'
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out
        uses: actions/checkout@v2
      -
        name: Build and push Docker Image to Github
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: direwolf
          addLatest: true
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          githubOrg: Wildsong
        
