on:
  push:
    branches:
      - 'main'
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - 
        name: Build and push Docker Image to the Hub
        id: buildx
        uses: mr-smithers-excellent/build-and-push@v5
        with:
          image: ${{ secrets.DOCKER_ORGANIZATION }}/direwolf
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
